version: '3'
services:

  ## SPRING API
  spring_api_app:
    image: docker_spring_api_app
    build:
      context: .
    container_name: app
    env_file:
      - .env.local
    ports:
      - 8080:8080
    depends_on:
      - twitter_postgres
      - twitter_redis

  ## DATABASE
  twitter_postgres:
    image: postgres:13.3
    container_name: twitter_postgres
    logging:
      driver: none
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    ports:
      - "35432:5432"
    volumes:
      - twitter-postgres:/var/lib/postgresql/data

  twitter_redis:
    image: redis:5.0-alpine
    command: redis-server --save 20 1 --loglevel warning
    container_name: twitter_redis
    logging:
      driver: none
    ports:
      - '6379:6379'
    volumes:
      - twitter-redis:/data

volumes:
  twitter-postgres:
  twitter-redis:
